name: look CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set-up-go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
          cache: true

      - name: build
        run: go build -v ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set-up-go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
          cache: true

      - name: spin-up-mongodb
        run: docker run -d -p 27017:27017 mongo:latest

      - name: test
        run: go test -v ./...
